- name: Installing Git on gitserver
  hosts: gitserver
  become: yes
  become_method: sudo

  tasks:
  - name: install git package
    yum: name={{ item }} update_cache=yes state=latest
    with_items:
    - git

- name: Installing Jenkins on jenkinsserver
  hosts: jenkinsserver
  gather_facts: true
  become: yes
  become_method: sudo
  tasks:
  - name: install git
    become: true
    command: yum update -y
    command: yum install git -y

  - name: Install dependencies
    yum: name=git update_cache=yes state=latest
    yum: name=wget update_cache=yes state=latest

  - name: Install java
    yum: name=java-1.8.0 update_cache=yes state=latest

  - name: Download jenkins repo
    command: wget -O /etc/yum.repos.d/jenkins.repo  https://pkg.jenkins.io/redhat-stable/jenkins.repo


  - name: Import Jenkins CI key 
    rpm_key:
      key: https://pkg.jenkins.io/redhat/jenkins.io.key
      state: present

  - name: Install Jenkins
    command: yum install jenkins -y
    become: true

  - name: Allow port 8080
    shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT

  - name: Start the server 
    service:
      name: jenkins
      state: started

  - name: Wait until the file /var/lib/jenkins/secrets/initialAdminPassword is present before continuing
    wait_for:
      path: /var/lib/jenkins/secrets/initialAdminPassword

  - name: Jenkings password
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: out
  
  - debug: var=out.stdout_lines

- name: Installing Docker on dockerserver
  hosts: dockerserver
  become: yes
  become_method: sudo
 
  tasks:
  - name: Add Docker repository
    command: yum install docker -y

  - name: install packages
    yum:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    with_items:
      - python
      - java-1.8.0
      - git

  - name: Start Docker service 
    service:
      name: docker
      state: started
      enabled: yes

  - name: Install python package
    command: easy_install docker-py

  - name: copy the lines 
    lineinfile:
      dest: /lib/systemd/system/docker.service
      regexp: '^ExecStart='
      line: 'ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock'

  - name: Reload systemd
    command: systemctl daemon-reload

  - name: docker restart
    service:
      name: docker
      state: restarted


